### ISSUE TITLE
Right most "Review" Item unreadable

### ISSUE THREAD

**Issue by RompingDogs** [DarwinsDogs/DD_SurveyPages#3]
Browser Firefox 43.0 on Mac OSX laptop. 
<img width="895" alt="screen shot 2016-08-23 at 8 54 01 am" src="https://cloud.githubusercontent.com/assets/21201361/17899189/4ffa1f0e-690f-11e6-9e43-4a936c63ea7d.png">

**Comment by DarwinsDogs** [comment]
This overlaps with the inconsistent spacing issue.  As the text above the bar has been resolved, I'll close this issue - but see the note in the inconsistent spacing issue about dog names below the bar still being an open issue.
