### ISSUE TITLE
Cannot advance to last questionnaire page 

### ISSUE THREAD

**Issue by laurazabsmith** [DarwinsDogs/DD_SurveyPages#5]
answer first 11 questions in Canine Eccentricities survey  
right arrow button is enabled, but clicking does not advance to the last page.  

![image](https://cloud.githubusercontent.com/assets/11576460/17899445/5bde1d38-6929-11e6-8012-7207ae24adc7.png)

Browser tested: chrome Version 52.0.2743.116 m

**Comment by DarwinsDogs** [comment]
Fixed by commit e62495c
