### ISSUE TITLE
"Rarely" Review Item unreadable. 

### ISSUE THREAD

**Issue by RompingDogs** [DarwinsDogs/DD_SurveyPages#6]
Browser: FF 43.0, Mac OS X Laptop

<img width="880" alt="screen shot 2016-08-23 at 9 19 46 am" src="https://cloud.githubusercontent.com/assets/21201361/17900144/e03fd6a0-6912-11e6-9b55-84e168078a1f.png">

**Comment by DarwinsDogs** [comment]
Good old off-by-one errors.  This should be patched up now.
