### ISSUE TITLE
Left Most Review Items unreadable

### ISSUE THREAD

**Issue by RompingDogs** [DarwinsDogs/DD_SurveyPages#7]
FF 43.0 browser on Mac OS X Laptop. 
Review item is "Independence"
<img width="893" alt="screen shot 2016-08-23 at 9 22 22 am" src="https://cloud.githubusercontent.com/assets/21201361/17900216/3b81528c-6913-11e6-9da3-e910ae84da08.png">

**Comment by DarwinsDogs** [comment]
Fixed with most recent push.  Items in general can get squished which is a more general issue, but there was a bug leading to a "zeroth" item being drawn.
